ALTER TABLE games ADD COLUMN model_checks TEXT NOT NULL DEFAULT '';
ALTER TABLE games ADD COLUMN model_resolve TEXT NOT NULL DEFAULT '';
ALTER TABLE games ADD COLUMN model_prose TEXT NOT NULL DEFAULT '';
